### ISSUE TITLE
Shouldn't allow adding conditions unless numOutcomes > 1

### ISSUE THREAD

**Issue by cag** [gnosis/hg-contracts#35]
@jakub-wojciechowski I realized that this is necessary because outcome collections are

> A nonempty proper subset of a condition’s outcome slots

And a set with one element has no nonempty _proper_ subsets. Basically, you can't use a condition with one element as an escrow mechanism.

Refer to #22 for more context.

**Comment by jakub-wojciechowski** [comment]
Thanks for pointing it out @cag. I've looked deeper and although we could allow accepting a single outcome slots by softening the split/merge restrictions: 

'''
require(indexSet > 0 && indexSet <= fullIndexSet, "got invalid index set");
'''

then we will end up with having a condition that constitutes a full set, so could be instantly merged and receive the collateral without reporting the results. It makes it totally unusable as an escrow. 

To cut the long story short, I agree and will submit a PR shortly.

**Comment by jakub-wojciechowski** [comment]
PR has been added to address it: https://github.com/gnosis/hg-contracts/pull/36
