### ISSUE TITLE
Gas & Codechecks 

### ISSUE THREAD

**Issue by cgewecke** [gnosis/hg-contracts#52]
@cag. Just opening and closing this to say hi :)

Very excited you're using the gas reporter in CI. It's kind of new so if you see any missing/incorrect data, weirdness, or think of any info that would be helpful to add, will you lmk over [there](https://github.com/cgewecke/eth-gas-reporter)? 

Thanks so much.

**Comment by cag** [comment]
Oh yeah! Before I forget again, I spent some time figuring out that it needs a newish version of Truffle with metadata in the contracts. So yeah that would be a good thing to mention in the docs...

**Comment by cgewecke** [comment]
@cag Ah nice, thank you, gotta fix that.
